### ISSUE TITLE
Acitivity fails to start

### ISSUE THREAD

**Issue by Hrishi1999** [cristian99garcia/gmail-activity#30] opened 2018-11-05 14:25 UTC
The activity won't start probably because of wrong signal name while porting to WebKit2. (https://github.com/sugarlabs/gmail-activity/pull/28)

Log : 
```Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 220, in <module>
    main()
  File "/usr/bin/sugar-activity", line 215, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/bin/sugar-activity", line 48, in create_activity_instance
    activity = constructor(handle)
  File "/home/hrishi/gmail-activity/activity.py", line 44, in __init__
    self.canvas = GmailCanvas()
  File "/home/hrishi/gmail-activity/canvas.py", line 90, in __init__
    self.login_screen = LoginScreen()
  File "/home/hrishi/gmail-activity/login_screen.py", line 45, in __init__
    self.browser.connect("web_process_terminated", self._web_process_terminated_cb)
TypeError: <browser.Browser object at 0x7f4718df5be0 (browser+Browser at 0x5639ecbb8400)>: unknown signal name: web_process_terminated```

**Comment by quozl** [comment] 2018-11-06 21:03
@tonadev, please fix.

**Comment by tonadev** [comment] 2018-11-06 21:09
Ok. I will fox

**Comment by tonadev** [comment] 2018-11-06 21:11
I will fix it and test it but I need to know how to login.  When login it gives me a code, what should I do next?

**Comment by quozl** [comment] 2018-11-06 22:38
I've no idea, I've never run this activity.  Read and analyse the source code associated with the login.

**Comment by cvgarciarea** [comment] 2018-11-07 12:06
Hi @tonadev, it's supposed to login you automatically, if the activity doesn't do that and show you a code, it's not working as it was expected.
I thought that this error was fixed in 312d4dfaab7e72a4bf11c9081afe76e0f6c1a1ff. You now know where the problem is.

**Comment by tonadev** [comment] 2018-11-11 00:58
@cristian99garcia Yeah, it was my port problem. I fixed it. However now I'm facing a new issue, when I open a mail, all the info appears(like the date, title, etc) but the message doesn't. I need to know if that it's my error, does it happen without the webkit port?

**Comment by cvgarciarea** [comment] 2018-11-11 12:48
@tonadev it doesn't happened to me when I was developing this activity (before the webkit port), but I can't say the webkit port broke it (basically because I don't know).

**Comment by quozl** [comment] 2018-11-11 23:56
Thanks all.  Issue as reported by @Hrishi1999 is fixed now that the previous pull request is reverted, so I'll close the issue.

The other problem identified by @tonadev above and in https://github.com/sugarlabs/gmail-activity/pull/32 will probably block further development; if anyone is interested in the problem, please feel free to do something about it.

**Closed as completed by quozl** 2018-11-11 23:56 UTC
